### ISSUE TITLE
Sentence split missing?

### ISSUE THREAD

**Issue by PhilipMay** [GermanT5/corpus#3]
Hi @stefan-it 

you write:

> We use the previously released [GC4](https://german-nlp-group.github.io/projects/gc4-corpus.html) corpus as main backbone for training our German T5 model.

My question is: Should a sentence splitting be done to train T5?

**Comment by stefan-it** [comment]
I have no strong opinion on that. 

But maybe @craffel has some experimence with sentence splitting from the T5 experiments 🤔

**Comment by craffel** [comment]
We didn't do sentence splitting - I don't think it would be helpful.

**Comment by PhilipMay** [comment]
Ok Thanks @craffel 

closing...
